#include <burglary_system>
#include <tower_system>

#include <stores_system>
#include <police_system>
#include <jailcell_system>
#include <cityhall_system>
#include <hospital_system>
#include <crack_system>
#include <weed_system>
#include <army_system>
#include <bomb_shop>
#include <car_crane>
#include <1v1_system>

#include <atm_robbery>

// Player jobs
#include <jobs>

// mini games & fun
#include <slot-machine_system>
#include <lotto_system>
#include <moneybag_system>