#define TD_OUTLINE_COLOUR			(0x00000088)

// Colours
#define COLOR_SAMPBLUE				0xa9c4e4FF

#define COLOR_YELLOW				0xFFFF00FF
#define COLOR_FUCHSIA				0xFF00FFFF
#define COLOR_RED					0xE85454FF
#define COLOR_GREEN					0x33AA33FF
#define COLOR_BLUE					0x33CCFFFF
#define COLOR_ORANGE				0xFFAA00FF
#define COLOR_GREY					0xAFAFAFFF
#define COLOR_PINK					0xFFC0CBFF
#define COLOR_NAVY					0x000080FF
#define COLOR_GOLD					0xB8860BFF
#define COLOR_LIGHTGREEN			0x00FD4DFF
#define COLOR_TEAL					0x008080FF
#define COLOR_BROWN					0xA52A2AFF
#define COLOR_AQUA					0xF0F8FFFF
#define COLOR_PURPLE				0xC2A2DAAA
#define COLOR_BLACK					0x000000FF
#define COLOR_WHITE					0xFFFFFFFF
#define COLOR_MODERATION            0xF5129FFF

// Embedding Colours
#define C_SAMPBLUE 		            "{a9c4e4}"
#define C_YELLOW					"{FFFF00}"
#define C_FUCHSIA					"{FF00FF}"
#define C_RED						"{E85454}"
#define C_GREEN						"{33AA33}"
#define C_BLUE						"{33CCFF}"
#define C_PURPLE                    "{C2A2DA}"
#define C_ORANGE					"{FFAA00}"
#define C_GREY						"{AFAFAF}"
#define C_PINK						"{FFC0CB}"
#define C_NAVY						"{000080}"
#define C_GOLD						"{B8860B}"
#define C_LGREEN					"{00FD4D}"
#define C_TEAL						"{008080}"
#define C_BROWN						"{A52A2A}"
#define C_AQUA						"{F0F8FF}"
#define C_MODERATION                "{F5129F}"

#define C_BLACK						"{000000}"
#define C_WHITE						"{FFFFFF}"