
#include <ui_connect-msg>
#include <ui_fpspingpacket>
#include <ui_info-box>
#include <ui_wanted-lvl>
#include <ui_class-selection>
#include <ui_peds>
//#include <ui_tdmenu>
#include <ui_time-left>
#include <ui_location>
#include <ui_error>

// Do not change the order
// we prioritise 'ui_prev-dialog'
#include <ui_prev-dialog>
#include <YSI_Visual\y_dialog>

#include <ui_dealership>
#include <ui_gametime>
#include <ui_money-notification>